### ISSUE TITLE
FYI this library is compatible with all versions of PHP 5

### ISSUE THREAD

**Issue by ozh** [jakeasmith/http_build_url#12]
Just leaving this as a comment for anyone who would wonder about the PHP requirements of this library: it works from [PHP 5.0.0 to 5.6.8 and 7](http://3v4l.org/oYmU9)

**Comment by jakeasmith** [comment]
Thanks for this! I added PHP 7 to the [test suite](https://github.com/jakeasmith/http_build_url/blob/master/.travis.yml). I would've added 5.0-5.3 but Travis doesn't have support for that.

**Comment by ozh** [comment]
Actually you can put 5.2 on Travis
See for instance how I managed to do it with [this library](https://github.com/ozh/bookmarkletgen/blob/master/.travis.yml), the trick is to install composer stuff with PHP 5.3+ then switch to 5.2 for the tests, which is only a matter of:
```
before_install:
    - phpenv global 5.5
    - composer stuff
    - phpenv global "$TRAVIS_PHP_VERSION"
```

**Comment by jakeasmith** [comment]
Aha! Added PHP 5.2. Thanks! https://travis-ci.org/jakeasmith/http_build_url/builds/61457214
